# Set Fish as the default command/shell
command = /usr/bin/fish

# RIGHT-CLICK
right-click-action = copy-or-paste


# Change cursor from block to line (bar)
cursor-style = bar


# Enlarge default window size (columns x rows)
window-width = 140
window-height = 35


# Enlarge default font size (default is usually 12 or 13)
font-size = 12


# Misc ---
window-theme = ghostty
shell-integration = fish
mouse-scroll-multiplier = 10


# Split ---
unfocused-split-opacity = 0.85
unfocused-split-fill = #FFFFFF


# Notifications ---
app-notifications = no-clipboard-copy


# Keybindings ---
## New Tab (removed ctrl+t as it conflicts with Opencode)
keybind = ctrl+shift+t=new_tab

## Close Tab & Split
keybind = ctrl+shift+q=close_surface

## Next Tab
keybind = ctrl+tab=next_tab

## Splits
keybind = ctrl+shift+s=new_split
keybind = ctrl+shift+]=goto_split:next
keybind = ctrl+shift+[=goto_split:previous
