[helpers]

[default]
depends = []

[default.files]
# Arf
"arf.toml" = "~/.config/arf/arf.toml"

# Ghostty
"ghostty.conf" = "~/.config/ghostty/config"

# Yazi file manager
"yazi.toml" = "~/.config/yazi/yazi.toml"

# Cursor
"cursor/settings.json" = "~/.config/Cursor/User/settings.json"
"cursor/keybindings.json" = "~/.config/Cursor/User/keybindings.json"

# Antigravity
"antigravity/settings.json" = "~/.config/Antigravity/User/settings.json"
"antigravity/keybindings.json" = "~/.config/Antigravity/User/keybindings.json"

# Positron
"positron/settings.json" = "~/.config/Positron/User/settings.json"
"positron/keybindings.json" = "~/.config/Positron/User/keybindings.json"

# Zed
"zed/settings.json" = "~/.config/zed/settings.json"
"zed/keymap.json" = "~/.config/zed/keymap.json"

# Arkenfox (Firefox hardenning)
"firefox/user-overrides.js" = "~/.mozilla/firefox/023rvj2f.default-release/user-overrides.js"

# Fish shell
"fish/config.fish" = "~/.config/fish/config.fish"

# Claude Code
"claude-code/CLAUDE.md" = "~/.claude/CLAUDE.md"
"claude-code/commands/" = "~/.claude/commands/"
"claude-code/statusline-zai.sh" = "~/.claude/statusline-zai.sh"
"claude-code/skills/" = "~/.claude/skills/"

# OpenCode
"opencode/oh-my-opencode.json" = "~/.config/opencode/oh-my-opencode.json"

[default.variables]

[settings]
default_target_type = "symbolic"
